// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXusYJE5fKQHGa8OCJetqj6VQntXvU45A',
    appId: '1:207292100875:web:997cbade9b75f92547720e',
    messagingSenderId: '207292100875',
    projectId: 'literasime-b86cf',
    authDomain: 'literasime-b86cf.firebaseapp.com',
    storageBucket: 'literasime-b86cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdnnXiBwnjZjBDntMqjWxymfHi8rQ2QW8',
    appId: '1:207292100875:android:c5ecc57131f04d7f47720e',
    messagingSenderId: '207292100875',
    projectId: 'literasime-b86cf',
    storageBucket: 'literasime-b86cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIYIXFeoRVYPBsPxDrSa2wCjhqibkQok',
    appId: '1:207292100875:ios:f6bf64bbb75da5ea47720e',
    messagingSenderId: '207292100875',
    projectId: 'literasime-b86cf',
    storageBucket: 'literasime-b86cf.firebasestorage.app',
    androidClientId: '207292100875-5k8o6g8e8hr7emu2v0i7sel5ig3p8mij.apps.googleusercontent.com',
    iosClientId: '207292100875-d5vip4f56kuu3b5rt39gemj906nhncuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.literasime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQIYIXFeoRVYPBsPxDrSa2wCjhqibkQok',
    appId: '1:207292100875:ios:f6bf64bbb75da5ea47720e',
    messagingSenderId: '207292100875',
    projectId: 'literasime-b86cf',
    storageBucket: 'literasime-b86cf.firebasestorage.app',
    androidClientId: '207292100875-5k8o6g8e8hr7emu2v0i7sel5ig3p8mij.apps.googleusercontent.com',
    iosClientId: '207292100875-d5vip4f56kuu3b5rt39gemj906nhncuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.literasime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXusYJE5fKQHGa8OCJetqj6VQntXvU45A',
    appId: '1:207292100875:web:c5cfea6887af013b47720e',
    messagingSenderId: '207292100875',
    projectId: 'literasime-b86cf',
    authDomain: 'literasime-b86cf.firebaseapp.com',
    storageBucket: 'literasime-b86cf.firebasestorage.app',
  );
}
